version: '3.8'
services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: wedding_booking_staging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  nodejs-app:
    build: ./booking-be
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/wedding_booking_staging
      NODE_ENV: staging  # Set NODE_ENV as required, change to production as needed
    ports:
      - "3001:3001"
    restart: always

  rails-app:
    build: ./booking-ruby-cms
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/wedding_booking_staging
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:-$(docker run --rm ruby:3.2.0-slim rails secret)}"
      RAILS_ENV: staging
    ports:
      - "3002:3002"
    restart: always

  react-app:
    build: ./booking-fe
    ports:
      - "80:80"
    restart: always

volumes:
  postgres-data:
