development:
  cloud_name: dyilvah0c
  api_key: "555743156499987"
  api_secret: "Av4JruXYMwwzER3HlBzD6Jvziy0"
staging:
  cloud_name: dyilvah0c
  api_key: "555743156499987"
  api_secret: "Av4JruXYMwwzER3HlBzD6Jvziy0"